#!/usr/bin/env bash
# scripts/gen-policy.sh — Generate AppArmor profiles from AIOS capability files
#
# Reads OS/etc/perms.d/aura.caps (and any OS/etc/perms.d/users/*.caps) and
# emits a corresponding AppArmor profile that enforces the capability set.
#
# Usage:
#   bash scripts/gen-policy.sh [--caps <caps-file>] [--output <profile-file>]
#
# Output: AppArmor profile suitable for loading with:
#   sudo apparmor_parser -r <profile-file>

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OS_ROOT="${OS_ROOT:-${REPO_ROOT}/OS}"
AIOS_HOME="${AIOS_HOME:-${REPO_ROOT}}"

OUTPUT_DIR="${REPO_ROOT}/build/apparmor"
mkdir -p "${OUTPUT_DIR}"

info() { printf '[gen-policy] %s\n' "$*"; }
die()  { printf '[gen-policy] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Map AIOS capabilities to AppArmor rules
# ---------------------------------------------------------------------------
_caps_to_apparmor_rules() {
    local caps_file="$1"
    local aios_root="$2"
    while IFS= read -r cap; do
        [[ -z "${cap}" || "${cap}" == \#* ]] && continue
        case "${cap}" in
            fs.*)
                echo "  ${aios_root}/OS/var/** rw,"
                echo "  ${aios_root}/OS/proc/** r,"
                ;;
            proc.*)
                echo "  capability kill,"
                echo "  ptrace read,"
                ;;
            net.*|vpn.*)
                echo "  network inet stream,"
                echo "  network inet dgram,"
                ;;
            log.*)
                echo "  ${aios_root}/OS/var/log/** rw,"
                ;;
            memory.*)
                echo "  ${aios_root}/OS/proc/aura/memory/** rw,"
                ;;
            system.*)
                echo "  /proc/uptime r,"
                echo "  /proc/meminfo r,"
                ;;
            ai.*)
                echo "  ${aios_root}/ai/** r,"
                ;;
            health.*)
                echo "  /proc/stat r,"
                echo "  /proc/uptime r,"
                ;;
            repair.*)
                echo "  ${aios_root}/** rw,"
                ;;
            upgrade.*)
                echo "  ${aios_root}/** rw,"
                ;;
        esac
    done < "${caps_file}"
}

# ---------------------------------------------------------------------------
# Generate profile for a caps file
# ---------------------------------------------------------------------------
gen_profile() {
    local caps_file="$1"
    local profile_name; profile_name="aios-$(basename "${caps_file}" .caps)"
    local output="${OUTPUT_DIR}/${profile_name}"

    info "Generating AppArmor profile: ${profile_name} → ${output}"

    cat > "${output}" <<HEADER
# Auto-generated by scripts/gen-policy.sh
# Source: ${caps_file}
# Do not edit manually — regenerate with: bash scripts/gen-policy.sh

profile ${profile_name} flags=(attach_disconnected) {
  # --- Base rules ---
  /bin/** ix,
  /usr/bin/** ix,
  /usr/local/bin/** ix,
  /lib/** r,
  /usr/lib/** r,
  /etc/ld.so.conf r,
  /etc/ld.so.conf.d/ r,
  /proc/self/** r,
  /dev/null rw,
  /dev/urandom r,

  # --- AIOS binary ---
  ${AIOS_HOME}/bin/aios ix,
  ${AIOS_HOME}/bin/aios-sys ix,
  ${AIOS_HOME}/lib/** r,
  ${AIOS_HOME}/ai/core/** r,
  ${AIOS_HOME}/etc/aios.conf r,

  # --- Capability-derived rules ---
HEADER

    _caps_to_apparmor_rules "${caps_file}" "${AIOS_HOME}" >> "${output}"

    cat >> "${output}" <<FOOTER
}
FOOTER

    info "Profile written: ${output}"
    echo "${output}"
}

# ---------------------------------------------------------------------------
# Process all caps files
# ---------------------------------------------------------------------------
GENERATED=0

for caps in "${OS_ROOT}/etc/perms.d/aura.caps" \
            "${OS_ROOT}/etc/perms.d/operator.caps" \
            "${OS_ROOT}/etc/perms.d/service.caps" \
            "${OS_ROOT}/etc/perms.d/users/"*.caps; do
    [[ -f "${caps}" ]] || continue
    gen_profile "${caps}"
    GENERATED=$(( GENERATED + 1 ))
done

if [[ "${GENERATED}" -eq 0 ]]; then
    info "No .caps files found in ${OS_ROOT}/etc/perms.d/ — nothing generated."
    exit 0
fi

echo ""
info "Generated ${GENERATED} AppArmor profile(s) in ${OUTPUT_DIR}/"
echo ""
echo "  Load profiles:"
echo "    sudo apparmor_parser -r ${OUTPUT_DIR}/aios-*"
echo ""
echo "  Enforce (production):"
echo "    sudo aa-enforce ${OUTPUT_DIR}/aios-*"
